#!/bin/bash

# Clone bioptim
git clone https://github.com/pyomeca/bioptim.git

# Install ACADOS
source activate notebook
cd bioptim/external
./acados_install_linux.sh
cd ../..

# Keep only the examples
mv bioptim/examples examples 
rm -rf bioptim

# Move the relevent model to a models folder
mkdir models
mv examples/getting_started/pendulum.bioMod models/
