#!/bin/bash

# Clone bioptim
git clone https://github.com/pyomeca/bioptim-tutorial.git

# Install ACADOS
cd bioptim/external
./acados_install_linux.sh
mv ../..

# Keep only the examples
mv bioptim/examples examples 
# rm -rf bioptim
